@baseUrl = http://localhost:5000/attributes

POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json

{
    "attribute_name": "Size"
}

###
POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json

{
    "attribute_name": "Color"
}

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/1

###
PUT {{baseUrl}}/update/1 HTTP/1.1
Content-Type: application/json

{
    "attribute_name": "color"
}

###
DELETE {{baseUrl}}/delete/2 HTTP/1.1
Content-Type: application/json